#!/usr/bin/env python
from JAK.Application import JWebApp

def vlearn_online():
    url = "http://vlearn.veltech.edu.in"

    webapp = JWebApp(title="Vlearn", web_contents=url, online=True)

    return webapp


vlearn_online().run()

